spring.application.name=HotelBooking
server.port=7070

## dB connection - postgreSQL ##
spring.datasource.url=jdbc:postgresql://localhost:5432/htl_bukin
spring.datasource.username=josh_psql
spring.datasource.password=1902
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties for PostgreSQL
# This property tells Hibernate which SQL dialect to use for PostgreSQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# This property controls how Hibernate manages the database schema.
# Common values:
#   validate: validate the schema, makes no changes to the database.
#   update: update the schema.
#   create: creates the schema, destroying previous data.
#   create-drop: creates the schema at the beginning of the session and drops it at the end.
#   none: do nothing.
# Use 'update' with caution in production environments.
#spring.jpa.hibernate.ddl-auto=update

#show queries on console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true