spring.application.name=nobsv2
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
spring.datasource.username=josh
spring.datasource.password=1902
spring.datasource.driver-class-name=org.postgresql.Driver